config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/home'
  root 'posts#index'
  resources :posts, only: [:new, :create, :index, :show, :destroy]
  resources :posts do
    resources :comments, only: [:create]
  end  
  resources :users, only: [:show]
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates :video, presence: true
  mount_uploader :video, VideoUploader
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
# class CommentsController < ApplicationController
#   def create
#     @comment = Comment.create(comment_params)
#     redirect_to "/posts/#{comment.post.id}"
#   end

#   private
#   def comment_params
#     params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
#   end
# end


# class CommentsController < ApplicationController
#   def create
#     comment = Comment.create(comment_params)
#     redirect_to "/posts/#{comment.post.id}" 
#     # @comment = Comment.create(comment_params)
#     # respond_to do |format|
#     #   format.html { redirect_to post_path(params[:post_id])  }
#     #   format.json
#     # end
#   end

#   private
#   def comment_params
#     params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
#   end
# end
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    post = Post.find(params[:post_id])
    @comment = post.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path)
    else
      flash[:success] = "コメントできませんでした"
      redirect_back(fallback_location: root_path)
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:content, :post_id, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :destroy]
  before_action :move_to_index, except: [:index, :show]
  # before_action :signed_in_user, only: [:show, :destroy]
  # before_action :correct_user,   only: [:show, :destroy]
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path, nothice: '投稿しました'
    else
      render :new
    end
  end

  def index
    @posts = Post.all.order('created_at DESC')
    # @posts = Post.includes(:user)
  end

  def show
    # @comment = Comment.new
    # @comments = @post.comments.includes(:user)
    @post = Post.find(params[:id])
    @comments = @post.comments.order('created_at DESC')
    @comment = @post.comments.build
  end

  def destroy
    post = Post.find(params[:id])
    if post.destroy
      redirect_to root_path, notice: '削除しました'
    else
      render :index
    end
    # @group = Group.find(params[:id])
    # @post = post.find(params[:id])
  end

  private
    def post_params
      params.require(:post).permit(:title, :body, :video).merge(user_id: current_user.id)
    end

    def set_post
      @post = Post.find_by(id: params[:id])
    end

    def move_to_index
      redirect_to action: :index unless user_signed_in?
    end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user,   only: [:show, :destroy]

  def destroy
  end

  def show
    @nickname = current_user.nickname
    @posts = current_user.posts
  end

  private
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Movie
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render partial: 'partial/navbar'
    .container
      = yield

app/views/pages/home.html.haml
%p このページはトップページです
= link_to "仮のボタンです", "#", class: "btn btn-primary"

app/views/partial/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  = link_to "swimlog", root_path, class: "navbar-brand"
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
    %form.form-inline.my-2.my-lg-0
      = link_to "投稿する", new_post_path, class: "new-post btn btn-info"
  - if user_signed_in?
    .user_nav.grid-6
      
      %ul.user__info.disply_flex
        %li
          .user_css
            = current_user.nickname
        %li
          = link_to "マイページ", "/users/#{current_user.id}", class: "new-post btn btn-info"
        %li
          = link_to "ログアウト", destroy_user_session_path,method:   :delete, class: "new-post btn btn-info"
        %li
          = link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class: "new-post btn btn-info"

  - else
    .grid-6
    %li
      = link_to "ログイン", new_user_session_path, class: 'new-post btn btn-info'
    %li
      = link_to "登録する", new_user_registration_path, class: 'new-post btn btn-info'
    %li
      = link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class: "new-post btn btn-info"

app/views/posts/index.html.haml
-# %p#notice= notice
-# %ul.list-unstyled
-#   - @posts.each do |post|
-#     %li.media
-#       = link_to post_path(post) do
-#         = video_tag post.video.to_s, :size => "360x200"
-#       .media-body
-#         = link_to post_path(post) do
-#           %h5.mt-0.mb-1= post.title
-#         = post.body

.contents.row
  .taro
  - @posts.each do |post|
    .content_post{:style => "background-video: url(#{post.video});"}
      .post_image
        = link_to post_path(post) do
          = video_tag post.video.to_s, class: "img"
          -# = video_tag post.video.to_s, :size => "360x200"
      %table.table.table-bordered
        %tr
          %th.col-sm
            = simple_format(post.body)
            %span.name
        %tr
          %th
            %a{:href => ""}
              %span 投稿者
              = post.user.nickname
        %tr
          %th
            .more
              %ul.more_list
                %li
                  = link_to '詳細', "/posts/#{post.id}", method: :get, class: "new-post btn btn-info"
                %li
                  = link_to '削除', "/posts/#{post.id}", method: :delete, class: "new-post btn btn-info"
                -# %li
                -#   = link_to '編集', "/posts/#{post.id}/edit", method: :get
      

app/views/posts/new.html.haml
= form_with(model: @post, local: true) do |form|
  .form-group
    = form.text_field :title, placeholder: "タイトル"
  .form-group
    = form.text_area :body, placeholder: "動画の説明"
  .form-group
    = form.file_field :video
  %button.btn.btn-primary{:type => "submit"} Submit

app/views/posts/show.html.haml
%div
  %h1= @post.title
%div
  %p= @post.body
#nicoscreen
  %iframe{:allow => "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", :allowfullscreen => "", :frameborder => "0", :height => "576", :src => "#{@post.video.to_s}", :width => "1024"}

-# %input#comment_text{:type => "text"}/
-# %button#comment_button.btn.btn-secondary コメント

-# - if current_user
-#   = form_tag("/posts/#{@post.id}/comments",  method: :post,  id: "new_comment" ) do
-#     %textarea.textbox{:cols => "30", :name => "text", :placeholder => "コメントする", :rows => "2"}
-#     %input.form__submit{:type => "submit", :value => "SEND"}/
-# - else
-#   %strong
-#     %p ※※※ コメントの投稿には新規登録/ログインが必要です ※※※

- if user_signed_in?
  = form_with(model: [@post, @comment], local: true) do |f|
    = f.text_area :content, class: "form-control", rows: 5
    = button_tag type: "submit", class: "btn btn-success float-right mt-1" do
      %i.far.fa-comments
      コメントする
%p コメント一覧
- @comments.each do |comment|
  %p= comment.content


%div
  = link_to '削除', @post, method: :delete, data: { confirm: '削除しますか?' }
#comment_list
  %ul#list.list-group

app/views/users/show.html.haml
.contents.row
  %p
    = @nickname
    さんの投稿一覧
  - @posts.each do |post|
    .content_post{:style => "background-video: url(#{post.video});"}
      = simple_format(post.body)
      %span.title= post.title